version: "3.9"
      
services:
    app:
        build: .
        volumes:
          - .:/code
        ports:
          - "8000:80"

        env_file:
            .env
        depends_on:
          - psql

    psql:
        image: postgres:12.1-alpine
        expose:
          - 5432
        volumes:
          - "psql_data:/var/lib/postgresql/data"
        environment:
          POSTGRES_USER: db
          POSTGRES_PASSWORD: db
          POSTGRES_DB: db
          
volumes:
  psql_data: {}